(function(){
  const weeks=[3,6,9,12,15,18,21,24,27,30];
  const dimensions=[['fluency','多種點子'],['flexibility','不同方法'],['originality','自己的新點子'],['elaboration','完整修改'],['evidence','證據說明'],['debugging','找錯重試'],['safety','AI 安全責任'],['expression','分享反思']];
  const read=key=>{try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}};
  const code=w=>String(w).padStart(2,'0');
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const collect=()=>weeks.map(week=>({week,feedback:read(`gifted-week-${code(week)}-understanding-v1`),rubric:read(`gifted-week-${code(week)}-rubric-v1`),depth:read(`gifted-week-${code(week)}-depth-v1`),reflection:localStorage.getItem(`gifted-week-${code(week)}-reflection`)||''}));
  let data=collect(),mode='teacher';
  const averages=()=>Object.fromEntries(dimensions.map(([key])=>{const values=data.map(x=>x.rubric?.scores?.[key]).filter(Number.isFinite);return[key,values.length?values.reduce((a,b)=>a+b,0)/values.length:0]}));
  const completed=()=>data.filter(x=>x.rubric?.confirmed).length;
  const evidenceCount=()=>data.filter(x=>x.rubric?.evidence||x.feedback?.observation||x.reflection).length;
  function renderSummary(){const avg=Object.values(averages()).filter(Boolean);document.querySelector('#summary').innerHTML=`<div class="metric"><b>${completed()} / 10</b><span>教師已確認週次</span></div><div class="metric"><b>${evidenceCount()} / 10</b><span>已有學習證據</span></div><div class="metric"><b>${avg.length?(avg.reduce((a,b)=>a+b,0)/avg.length).toFixed(1):'—'}</b><span>八項能力平均</span></div><div class="metric"><b>${data.filter(x=>x.feedback?.level).length} / 10</b><span>學生理解回饋</span></div>`;}
  function renderTable(){document.querySelector('#weekRows').innerHTML=data.map(item=>{const scores=Object.values(item.rubric?.scores||{});const avg=scores.length?(scores.reduce((a,b)=>a+Number(b),0)/scores.length).toFixed(1):'—';return`<tr><td>第 ${item.week} 週</td><td>${item.rubric?.confirmed?'已確認':'草稿'}</td><td>${avg}</td><td>${esc(item.rubric?.evidence||item.feedback?.observation||'尚無紀錄')}</td><td><a href="week-${code(item.week)}/#assessment">開啟</a></td></tr>`}).join('');}
  const scoreRows=()=>{const avg=averages();return dimensions.map(([key,label])=>`<tr><th>${label}</th><td>${avg[key]?avg[key].toFixed(1):'尚無資料'}</td><td>${avg[key]>=3.5?'能主動延伸與說明':avg[key]>=2.5?'能獨立完成主要任務':avg[key]>0?'仍需要教師引導與更多證據':'尚未評量'}</td></tr>`).join('')};
  const weeklyRows=()=>data.map(item=>`<tr><th>第 ${item.week} 週</th><td>${item.rubric?.confirmed?'教師已確認':'尚未確認'}</td><td>${esc(item.rubric?.evidence||'—')}</td><td>${esc(item.reflection||'—')}</td></tr>`).join('');
  function reportBody(){
    const avg=averages();const strengths=dimensions.filter(([key])=>avg[key]>=3).map(([,label])=>label);const next=dimensions.filter(([key])=>avg[key]>0&&avg[key]<3).map(([,label])=>label);
    if(mode==='parent')return`<h1>資訊科技課程學習摘要</h1><p>本學期透過十次雙節資訊科技課，學生從生活中的 AI、資料與公平出發，逐步練習清楚指令、Scratch 互動、AI 安全、作品設計、測試與分享。</p><h2>看見的成長</h2><p>${strengths.length?`目前較穩定的能力包括：${strengths.join('、')}。`:'目前仍在累積教師確認的學習證據。'}</p><h2>下一步</h2><p>${next.length?`接下來會繼續練習：${next.join('、')}。`:'接下來將透過不同例子與小研究，繼續挑戰更深入的思考。'}</p><h2>學習方式</h2><p>課程重視先自己想、動手測試、保留修改版本，再安全使用 AI 幫忙。分數不是唯一重點，能說明理由、使用證據與願意修正同樣重要。</p>`;
    if(mode==='school')return`<h1>115 學年度創造能力資優校本方案<br>資訊科技課程成果摘要</h1><p><b>授課教師：</b>黃凱揚老師　<b>學校：</b>桃園市龍潭區石門國民小學</p><p><b>實施方式：</b>十次雙節課，共 20 節；一對一探究、實作、測試與成果表達。</p><h2>課程成果</h2><p>學生完成 AI 判斷、資料整理、公平與隱私、演算法、Scratch 分類互動、提示詞比較、AI 倫理、原型製作、測試及成果發表等學習任務。</p><h2>能力表現</h2><table><thead><tr><th>評量面向</th><th>平均</th><th>證據摘要</th></tr></thead><tbody>${scoreRows()}</tbody></table><h2>評量原則</h2><p>以作品、測試、口頭說明、修改版本及教師觀察為依據；AI 僅協助整理文字，分數與判斷均由教師確認。</p>`;
    return`<h1>資訊科技課程教師學期紀錄</h1><p><b>教師確認週次：</b>${completed()}／10　<b>具學習證據週次：</b>${evidenceCount()}／10</p><h2>八項能力量規</h2><table><thead><tr><th>評量面向</th><th>平均</th><th>目前判讀</th></tr></thead><tbody>${scoreRows()}</tbody></table><h2>逐週證據</h2><table><thead><tr><th>週次</th><th>狀態</th><th>教師證據</th><th>學生反思</th></tr></thead><tbody>${weeklyRows()}</tbody></table><h2>教師綜合評語</h2><p id="finalCommentText">${esc(localStorage.getItem('gifted-annual-report-comment')||'請在下方輸入教師綜合評語。')}</p>`;
  }
  function renderReport(){document.querySelectorAll('[data-mode]').forEach(button=>button.classList.toggle('active',button.dataset.mode===mode));document.querySelector('#reportOutput').innerHTML=reportBody();}
  document.querySelector('.mode-switch').addEventListener('click',event=>{const button=event.target.closest('[data-mode]');if(!button)return;mode=button.dataset.mode;renderReport();});
  document.querySelector('#finalComment').value=localStorage.getItem('gifted-annual-report-comment')||'';
  document.querySelector('#finalComment').addEventListener('input',event=>{localStorage.setItem('gifted-annual-report-comment',event.target.value);renderReport();});
  document.querySelector('#reportConfirmed').checked=localStorage.getItem('gifted-annual-report-confirmed')==='true';
  document.querySelector('#reportConfirmed').addEventListener('change',event=>localStorage.setItem('gifted-annual-report-confirmed',String(event.target.checked)));
  document.querySelector('#printReport').onclick=()=>window.print();
  document.querySelector('#exportData').onclick=()=>{const payload={version:1,exportedAt:new Date().toISOString(),weeks:data,comment:localStorage.getItem('gifted-annual-report-comment')||'',confirmed:localStorage.getItem('gifted-annual-report-confirmed')==='true'};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='gifted-ai-lab-anonymous-report-data.json';link.click();URL.revokeObjectURL(link.href)};
  document.querySelector('#importFile').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{const payload=JSON.parse(await file.text());(payload.weeks||[]).forEach(item=>{if(item.feedback)localStorage.setItem(`gifted-week-${code(item.week)}-understanding-v1`,JSON.stringify(item.feedback));if(item.rubric)localStorage.setItem(`gifted-week-${code(item.week)}-rubric-v1`,JSON.stringify(item.rubric));if(item.depth)localStorage.setItem(`gifted-week-${code(item.week)}-depth-v1`,JSON.stringify(item.depth));if(item.reflection)localStorage.setItem(`gifted-week-${code(item.week)}-reflection`,item.reflection)});if(payload.comment)localStorage.setItem('gifted-annual-report-comment',payload.comment);data=collect();renderSummary();renderTable();renderReport();alert('匿名紀錄已匯入。')}catch{alert('無法讀取這份備份檔。')}});
  renderSummary();renderTable();renderReport();
})();
