(function(){
  const week=Number(document.body.dataset.week);
  const data=(window.GIFTED_WEEKS||[]).find(item=>item.week===week);
  const app=document.querySelector('#app');
  if(!data){app.innerHTML='<p class="loading">找不到本週課程資料。</p>';return;}
  const esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const ww=String(data.week).padStart(2,'0');
  const index=window.GIFTED_WEEKS.findIndex(item=>item.week===week);
  const prev=window.GIFTED_WEEKS[index-1],next=window.GIFTED_WEEKS[index+1];
  const localHref=href=>href.startsWith('../')?'../'+href:href;
  const flowGuide=['先收集學生原本的想法，不急著公布答案。','用具體例子操作，要求學生邊做邊說理由。','完成第一個可見產出，卡住時只給一個提示。','用一句話或畫面確認第一節理解。','把概念轉成可操作任務，先完成第一版。','加入反例、限制或錯誤輸入進行測試。','根據證據修改，保留前後版本。','依週次與版本命名存檔，說出今天的關鍵發現。'];
  document.title=`W${ww} ${data.title}｜石門智繪客`;
  app.innerHTML=`<header class="topbar"><div class="shell topbar-inner"><a class="brand" href="../index.html"><span class="brand-mark">W${ww}</span><span>石門智繪客｜週次專用駕駛艙</span></a><nav class="topnav">${prev?`<a class="nav-btn" href="../week-${String(prev.week).padStart(2,'0')}/" title="上一週">←</a>`:''}<a class="nav-btn wide" href="../index.html">總覽</a>${next?`<a class="nav-btn" href="../week-${String(next.week).padStart(2,'0')}/" title="下一週">→</a>`:''}</nav></div></header>
  <main class="shell"><section class="hero"><div><div class="code">WEEK ${ww} · ${esc(data.date)} · 90 MIN</div><h1>${esc(data.title)}</h1><p>${esc(data.goal)}</p></div><div class="output"><span>本週可見產出</span>${esc(data.output)}</div></section>
  <div class="actions"><a class="action primary" href="lecture-slides.html">開啟本週投影簡報</a><a class="action notebook" href="${esc(data.notebookUrl)}" target="_blank" rel="noopener">開啟本週 NotebookLM</a><a class="action" href="teacher-pack.pdf">下載本週直式詳案</a><button class="action" onclick="window.print()">列印本週</button></div>
  <nav class="tabs" role="tablist"><button class="tab active" data-view="teacher">教師流程</button><button class="tab" data-view="student">學生任務</button><button class="tab" data-view="media">NotebookLM 教材</button></nav>
  <section id="teacher" class="view active"><div class="summary"><div class="summary-cell"><b>核心概念</b>${esc(data.concept)}</div><div class="summary-cell"><b>課前準備</b>${esc(data.materials)}</div><div class="summary-cell"><b>授課設定</b>一對一教學｜連續兩節｜一般教室</div></div><section class="section"><h2>90 分鐘逐段流程</h2><div class="timeline">${data.timeline.map((row,i)=>`<div class="time-row"><div class="time">${esc(row[0])}</div><div class="time-main"><b>${esc(row[1])}</b><span>${esc(flowGuide[i])}</span></div><div class="time-tip">${esc(row[2])}</div></div>`).join('')}</div></section><section class="section"><h2>教師追問</h2><div class="questions">${data.questions.map(q=>`<div class="question">「${esc(q)}」</div>`).join('')}</div></section><section class="section"><h2>本週教學資源</h2><div class="resources">${data.links.filter(x=>x[1]&&!x[1].includes('notebooklm.google.com')).map(x=>`<a class="resource" href="${esc(localHref(x[1]))}"><b>${esc(x[0])} →</b><span>開啟相關互動教材</span></a>`).join('')}<a class="resource" href="${esc(data.notebookUrl)}" target="_blank" rel="noopener"><b>本週 NotebookLM →</b><span>只收錄本週詳案與相關教材</span></a><a class="resource" href="source.md"><b>NotebookLM 來源檔 →</b><span>本週研究焦點與完整授課內容</span></a></div></section><section class="section"><h2>課後銜接備忘</h2><textarea class="teacher-note" placeholder="學生今天最有力的推理、卡住的地方、下次要延續的線索…"></textarea></section></section>
  <section id="student" class="view"><div class="student-box"><h2>本週任務</h2><ol>${data.student.map(item=>`<li>${esc(item)}</li>`).join('')}</ol></div><section class="section"><h2>完成前自我檢查</h2><div class="self-check"><div class="check">我有保留第一版與修改版。</div><div class="check">我能說出選擇的理由。</div><div class="check">我有用測試或資料支持結論。</div><div class="check">使用 AI 時，我有查證並保護個資。</div></div></section><section class="section"><h2>今天要帶走的一句話</h2><textarea class="teacher-note student-reflection" placeholder="我原本以為……，現在我發現……"></textarea></section></section>
  <section id="media" class="view"><div class="media-grid"><video class="week-video" controls preload="metadata" poster="../assets/gifted-lab-cover.png"><source src="video.mp4" type="video/mp4"></video><div><div class="status-box"><b>本週 NotebookLM 短影片</b><span class="video-status">生成中；完成後會自動放入此處。</span></div><div class="resources" style="grid-template-columns:1fr;margin-top:10px"><a class="resource" href="slides.pdf"><b>NotebookLM 本週簡報 →</b><span>專屬本週的 8 至 12 頁教材</span></a><a class="resource" href="lecture-slides.html"><b>互動投影簡報 →</b><span>課堂全螢幕與觸控操作版本</span></a><a class="resource" href="${esc(data.notebookUrl)}" target="_blank" rel="noopener"><b>進入本週 NotebookLM →</b><span>繼續備課、提問與產出教材</span></a></div></div></div></section></main>
  <footer class="shell week-footer"><span>桃園市龍潭區石門國民小學 · W${ww} 資訊科技課程</span><span>Made with ❤️ by <a href="https://www.smes.tyc.edu.tw/modules/tadnews/page.php?ncsn=11&amp;nsn=16#a5" target="_blank" rel="noopener">阿凱老師</a></span></footer>
  <aside class="tool-dock"><div class="tools"><div class="tool-head"><span>課堂工具</span><button class="nav-btn close-tools">×</button></div><div class="timer-display">10:00</div><div class="timer-controls"><button data-min="5">5 分</button><button data-min="10">10 分</button><button data-min="15">15 分</button><button class="start-timer">開始</button></div><button class="action pick-challenge" style="width:100%;margin-top:10px">抽進階挑戰</button><p class="challenge">完成基本任務後，再抽一張挑戰卡。</p><button class="action draw-toggle" style="width:100%">開啟白板</button><div class="draw-wrap"><div class="draw-tools"><input type="color" value="#15383c" aria-label="畫筆顏色"><button class="clear-draw">清除</button></div><canvas class="draw-canvas"></canvas></div></div><button class="tool-toggle" aria-label="開啟課堂工具">⏱</button></aside>`;
  document.querySelector('.tabs').addEventListener('click',event=>{const tab=event.target.closest('[data-view]');if(!tab)return;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===tab));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===tab.dataset.view));});
  const note=document.querySelector('.teacher-note');const reflection=document.querySelector('.student-reflection');note.value=localStorage.getItem(`gifted-week-${ww}-note`)||'';reflection.value=localStorage.getItem(`gifted-week-${ww}-reflection`)||'';note.addEventListener('input',()=>localStorage.setItem(`gifted-week-${ww}-note`,note.value));reflection.addEventListener('input',()=>localStorage.setItem(`gifted-week-${ww}-reflection`,reflection.value));
  const tools=document.querySelector('.tools');document.querySelector('.tool-toggle').onclick=()=>tools.classList.toggle('open');document.querySelector('.close-tools').onclick=()=>tools.classList.remove('open');let seconds=600,timer=null;const display=document.querySelector('.timer-display');const show=()=>{display.textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`};document.querySelectorAll('[data-min]').forEach(button=>button.onclick=()=>{clearInterval(timer);timer=null;seconds=Number(button.dataset.min)*60;show();document.querySelector('.start-timer').textContent='開始'});document.querySelector('.start-timer').onclick=event=>{if(timer){clearInterval(timer);timer=null;event.target.textContent='開始';return}event.target.textContent='暫停';timer=setInterval(()=>{seconds=Math.max(0,seconds-1);show();if(!seconds){clearInterval(timer);timer=null;display.textContent='時間到';event.target.textContent='開始'}},1000)};
  const challenges=['找一個會讓目前規則失敗的反例。','提出兩種完全不同的解法並比較。','刪掉一項資料，看看結論是否改變。','把解釋改成一年級學生也聽得懂。','請 AI 反對你的想法，再逐點查證。','讓別人在沒有提示下操作你的作品。'];document.querySelector('.pick-challenge').onclick=()=>document.querySelector('.challenge').textContent=challenges[Math.floor(Math.random()*challenges.length)];
  const drawWrap=document.querySelector('.draw-wrap'),canvas=document.querySelector('.draw-canvas'),ctx=canvas.getContext('2d'),color=document.querySelector('.draw-tools input');let drawing=false;const resize=()=>{const rect=canvas.getBoundingClientRect();canvas.width=Math.max(1,Math.round(rect.width*devicePixelRatio));canvas.height=Math.max(1,Math.round(rect.height*devicePixelRatio));ctx.scale(devicePixelRatio,devicePixelRatio);ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=3};document.querySelector('.draw-toggle').onclick=()=>{drawWrap.classList.toggle('open');if(drawWrap.classList.contains('open'))resize()};const point=event=>{const rect=canvas.getBoundingClientRect(),touch=event.touches?.[0]||event;return{x:touch.clientX-rect.left,y:touch.clientY-rect.top}};const start=event=>{drawing=true;const p=point(event);ctx.beginPath();ctx.moveTo(p.x,p.y);event.preventDefault()};const move=event=>{if(!drawing)return;const p=point(event);ctx.strokeStyle=color.value;ctx.lineTo(p.x,p.y);ctx.stroke();event.preventDefault()};['pointerdown','touchstart'].forEach(name=>canvas.addEventListener(name,start,{passive:false}));['pointermove','touchmove'].forEach(name=>canvas.addEventListener(name,move,{passive:false}));['pointerup','pointerleave','touchend'].forEach(name=>canvas.addEventListener(name,()=>drawing=false));document.querySelector('.clear-draw').onclick=()=>ctx.clearRect(0,0,canvas.width,canvas.height);
  fetch('video.mp4',{method:'HEAD'}).then(response=>{if(response.ok)document.querySelector('.video-status').textContent='影片已完成，可直接播放。'}).catch(()=>{});
})();
